#!/bin/bash

E_OPTION_ERROR=1
E_SOURCE_FILE_NOT_FOUND=10
E_CANT_READ_SOURCE_FILE=8
E_SOURCE_TYPE_ERROR=21
E_INVALID_SOURCE_FILE=29
E_FAIL_ERROR=5
COMMAND=`basename $0`

# Set constants for formatting output
TXT_NORMAL=$(tput sgr0)
TXT_BOLD=$(tput bold)
TXT_COMMAND=$(tput setaf 4)
TXT_NOTICE=$(tput setaf 6)
TXT_SUCCESS=$(tput setaf 2)
TXT_WARNING=$(tput setaf 5; tput bold)
TXT_ERROR=$(tput setaf 1)
TXT_FAIL=$(tput setab 1; tput bold)
TXT_PROMPT=$(tput setaf 3)


##############################################################################
main()
##############################################################################
{
  # notify when any command fails
  add_on_fail 'printf "\n${TXT_FAIL}*****  $COMMAND FAILED  *****${TXT_NORMAL}\n\n"'

  get_options "$@"

  # move operand pointer past any options & reset OPTIND
  shift $(($OPTIND - 1))
  OPTIND=1

  if [[ -n "$source_file" ]]; then    # SOURCE_FILE mode:
    source_location="$source_file"
    source_type="file"
    backup_source=false
    get_operands_source_file "$@"
  else    # SOURCE_DATABASE mode:
    source_location=$source_db
    source_type="database"
    backup_source=true
    get_operands_source_database "$@"
  fi

  set_common_variables    # sets Comment, Username, Password, & Date

  check_db_connection

  prod_db_overwrite_test "a $source_type ('$source_location')"

  if $backup_source; then
    backup_source_db    # sets $source_db_output
    source_file="$source_db_output"
  fi

  if [[ -n "$destination_db" ]]; then
    backup_destination_db
    create_destination_db
    copy_source_to_destination_db "$source_file"
  fi

  # output line break for aesthatic purposes
  printf "\n"
}


##############################################################################
help_prompt()
##############################################################################
{
  printf "${TXT_NOTICE}Try \`$COMMAND -h' for more information${TXT_NORMAL}\n"
}


##############################################################################
usage()
##############################################################################
{
cat << EOF
usage: $COMMAND [OPTION]... SOURCE_DATABASE [DESTINATION_DATABASE]
       $COMMAND [OPTION]... -s SOURCE_FILE DESTINATION_DATABASE

DESCRIPTION:
   $COMMAND
      Backup of MySQL or PostgreSQL database from SOURCE_DATABASE and
      optionally copy to DESTINATION_DATABASE

   $COMMAND -s
      Copy SOURCE_FILE to DESTINATION_DATABASE

OPTIONS:
   -h                show this Help message
   -d[mp]            select [m]ySQL or [p]ostgreSQL database type (default: mySQL)
   -s <SOURCE_FILE>  copy from Source file to DESTINATION_DATABASE
   -c <COMMENT>      Comment to add to filename (default: <none>)
   -u <USERNAME>     database Username (default: root)
   -p <PASSWORD>     database Password (default: <prompt>)
   -p ''             database Password is not set (or null)
   -b                use Bzip2 to compress output
   -g                use Gzip to compress output
   -n                dry run - do Not actually do anything, just show what would be done
EOF
}


##############################################################################
get_options()
##############################################################################
{
  while getopts ":hd:s:c:u:p:bgn" opt; do
    case $opt in
      h)
        usage
        exit
        ;;
      d)
        case "${OPTARG}" in
          m|p)
            db_type="${OPTARG}"
            ;;
          *)
            printf "${TXT_ERROR}$COMMAND: Invalid option: -d$OPTARG${TXT_NORMAL}\n"
            help_prompt
            exit $E_OPTION_ERROR
            ;;
        esac
        ;;
      s)
        source_file="$OPTARG"
        ;;
      c)
        comment="$OPTARG"
        ;;
      u)
        username="$OPTARG"
        ;;
      p)
        password="$OPTARG"
        ;;
      b)
        use_bzip2=true
        ;;
      g)
        use_gzip=true
        ;;
      n)
        dry_run=true
        ;;
      \?)
        printf "${TXT_ERROR}$COMMAND: Invalid option: -$OPTARG${TXT_NORMAL}\n"
        help_prompt
        exit $E_OPTION_ERROR
        ;;
      :)
        printf "${TXT_ERROR}$COMMAND: Option -$OPTARG requires an argument.${TXT_NORMAL}\n"
        help_prompt
        exit $E_OPTION_ERROR
        ;;
    esac
  done
}


##############################################################################
get_operands_source_file()
##############################################################################
{
  # check for the right # of arguments
  case $# in
    0)
      printf "${TXT_ERROR}$COMMAND: missing DESTINATION_DATABASE operand${TXT_NORMAL}\n"
      help_prompt
      exit $E_OPTION_ERROR
      ;;
    1)
      destination_db=$1
      ;;
    *)
      printf "${TXT_ERROR}$COMMAND: too many operands${TXT_NORMAL}\n"
      help_prompt
      exit $E_OPTION_ERROR
      ;;
  esac
}


##############################################################################
get_operands_source_database()
##############################################################################
{
  # check for the right # of arguments
  case $# in
    0)
      printf "${TXT_ERROR}$COMMAND: missing SOURCE_DATABASE operand${TXT_NORMAL}\n"
      help_prompt
      exit $E_OPTION_ERROR
      ;;
    1)
      source_db=$1
      destination_db=
      ;;
    2)
      source_db=$1
      destination_db=$2
      ;;
    *)
      printf "${TXT_ERROR}$COMMAND: too many operands${TXT_NORMAL}\n"
      help_prompt
      exit $E_OPTION_ERROR
      ;;
  esac
}


##############################################################################
prod_db_overwrite_test()
##############################################################################
{
  source_comment=$1

  if [[ $destination_db =~ '_prod' ]]; then
    printf "\n${TXT_WARNING}*******************************************************************************\n"
    printf "*                            !!!!!  WARNING !!!!!                             *\n"
    printf "*                                                                             *\n"
    printf "* This script will overwrite a PRODUCTION database ($destination_db)\n"
    printf "* with the contents of $source_comment.\n"
    printf "*                                                                             *\n"
    printf "* Are you sure you want to do this?  If so, confirm by entering \"CONFIRM\" in  *\n"
    printf "* all caps (without the quotes) at the prompt below.                          *\n"
    printf "*******************************************************************************${TXT_NORMAL}\n"
    printf "\n"
    read -p "${TXT_PROMPT}Are you sure? ${TXT_NORMAL}" confirm

    if [[ $confirm != "CONFIRM" ]]; then
      printf "\n${TXT_ERROR}## Exiting program without making any changes${TXT_NORMAL}\n\n"
      exit 1
    fi
  fi
}


##############################################################################
set_common_variables()
##############################################################################
{
  set_comment_out
  set_db_type
  set_db_username
  set_db_password
  set_db_password_out
  set_date
}


##############################################################################
set_comment_out()
##############################################################################
{
  # if comment is set & not empty, create the comment output
  if [[ -n "$comment" ]]; then
    comment_out=".\"$comment\""
  fi
}


##############################################################################
set_db_type()
##############################################################################
{
  # set DB type to "m" (mysql) if not set with -d option
  if [[ -n "$db_type" ]]; then
    db_type=$db_type
  else
    db_type="m"
  fi
}


##############################################################################
set_db_username()
##############################################################################
{
  # set DB username to "root" if not set with -u option
  if [[ -n "$username" ]]; then
    db_username=$username
  else
    db_username="root"
  fi
}


##############################################################################
set_db_password()
##############################################################################
{
  # get & set DB password if not set with -p option
  if [[ -n "$password" ]]; then
    db_password=$password
  elif [[ -n "${password+isSet}" ]]; then
    db_password=
  else
    printf "\n"
    read -s -p "${TXT_PROMPT}DB Password for user '$db_username': ${TXT_NORMAL}" db_password
    printf "\n"
  fi
}


##############################################################################
set_db_password_out()
##############################################################################
{
  # if db_password is set & not empty, create the password output (use "-p")
  # include space in front, so it will be separated from the username output
  if [[ -n "$db_password" ]]; then
    db_password_out=" -p'$db_password'"
    db_password_out_hidden=" -p'<password>'"
  else
    db_password_out=
    db_password_out_hidden=
  fi
}


##############################################################################
set_date()
##############################################################################
{
  # get & set the date
  date=$(date +%F.%T)
}


##############################################################################
on_exit()
##############################################################################
{
  exitCode=$?

  if [[ $exitCode == $E_FAIL_ERROR ]]; then
    for i in "${on_fail_items[@]}"; do
      eval "$i"
    done
  fi

  exit $exitCode
}


##############################################################################
add_on_fail()
##############################################################################
{
  local n=${#on_fail_items[*]}
  on_fail_items[$n]="$*"
  if [[ $n -eq 0 ]]; then
    set -E -o pipefail
    trap on_exit EXIT
  fi
}


##############################################################################
output_command()
##############################################################################
{
  command=$1
  outfile=$2

  if [[ -n "$outfile" ]]; then
    command="$command > '$outfile'"
  fi

  command_out=${command//'<password>'/$db_password_out_hidden}

  printf "${TXT_PROMPT}> ${TXT_NORMAL}${TXT_COMMAND}$command_out${TXT_NORMAL}\n"
}


##############################################################################
_run_command()
##############################################################################
{
  command=$1

  command_run=${command/'<password>'/$db_password_out}

  if [[ -n "$dry_run" ]]; then
    printf "${TXT_NOTICE}  -- DRY RUN -- No Command Run${TXT_NORMAL}\n"
  else
    eval "$command_run" &
    pid=$!

    printf " "
    rotate='|/-\'

    while kill -n 0 $pid 2>/dev/null; do
      rotate="${rotate#?}${rotate%???}"
      printf '%.1s\b' "$rotate"
      sleep 0.125
    done

    printf "\b"
    wait $pid
  fi
}


##############################################################################
run_command()
##############################################################################
{
  command=$1
  outfile=$2
  error_handling=$3

  if [[ -n "$outfile" ]]; then
    command="$command > '$outfile'"
  fi

  _run_command "$command"
  return_code=$?

  if [[ $error_handling != "silent" ]]; then
    if [[ $return_code -eq 0 ]]; then
      printf "${TXT_SUCCESS}###   [ PASS ]   ###${TXT_NORMAL}\n"
    else
      printf "${TXT_ERROR}###   [ FAIL ]   ###${TXT_NORMAL}\n"
      if [[ "$error_handling" == "fail" ]]; then
        exit $E_FAIL_ERROR    # Trap Error & Exit
      fi
    fi
  fi

  return $return_code
}


##############################################################################
output_filename()
##############################################################################
{
  backup_type=$1
  database=$2

  output_filename="output.$backup_type:\"$database\".$date$comment_out.sql"

  echo $output_filename
}


##############################################################################
optionally_compress_file()
##############################################################################
{
  local file_reference=$1
  local filename=${!file_reference}
  local file_extension
  local return_code
  local command

  if [[ -n $use_bzip2 ]] && [[ $use_bzip2 == true ]]; then
    printf "\n${TXT_NOTICE}## Compressing file with bzip2: \"$filename\"${TXT_NORMAL}\n"

    command="bzip2 '$filename'"

    output_command "$command"

    run_command "$command" "" "fail"
    return_code=$?

    file_extension="bz2"

  elif [[ -n $use_gzip ]] && [[ $use_gzip == true ]]; then
    printf "\n${TXT_NOTICE}## Compressing file with gzip: \"$filename\"${TXT_NORMAL}\n"

    command="gzip '$filename'"

    output_command "$command"

    run_command "$command" "" "fail"
    return_code=$?

    file_extension="gz"
  fi

  if [[ -n $return_code ]] && [[ $return_code -eq 0 ]]; then    # rename the file
    filename="${filename}.${file_extension}"
    eval "$file_reference='$filename'"
  fi
}


##############################################################################
output_source_file_command()
##############################################################################
{
  source_file="$1"

  if [[ ! -e "$source_file" ]]; then
    exit $E_SOURCE_FILE_NOT_FOUND
  elif [[ ! -f "$source_file" ]]; then
    exit $E_INVALID_SOURCE_FILE
  elif [[ ! -r "$source_file" ]]; then
    exit $E_CANT_READ_SOURCE_FILE
  fi

  mime_type=$(file --brief --mime "$source_file")

  case $mime_type in
    *text/plain*)
      input_process="cat"
      ;;
    *bzip*)
      input_process="bzip2 -dc"
      ;;
    *gzip*)
      input_process="gzip -dc"
      ;;
    *)
      exit $E_SOURCE_TYPE_ERROR
      ;;
  esac

  redirection_input="${input_process} '$source_file'"

  echo $redirection_input
}


##############################################################################
backup_source_db()
##############################################################################
{
  printf "\n\n${TXT_NOTICE}## Creating dump of source database: \"$source_db\"${TXT_NORMAL}\n"

  # set source output filename
  source_db_output=$(output_filename 'source' "$source_db")

  case "${db_type}" in
    m)
      command="mysqldump -u '$db_username'<password> '$source_db'"
      ;;
    p)
      command="pg_dump -U '$db_username'<password> '$source_db'"
      ;;
  esac

  output_command "$command" "$source_db_output"
  run_command "$command" "$source_db_output" "fail"
  add_on_fail "rm -f '$source_db_output'"

  optionally_compress_file "source_db_output"    # sets $source_db_output to new filename
  add_on_fail "rm -f '$source_db_output'"
}


##############################################################################
check_db_connection()
##############################################################################
{
  printf "\n\n${TXT_NOTICE}## Checking database connection...${TXT_NORMAL}\n"

  # check if destination database exists
  command="mysql --batch --skip-column-names -u '$db_username'$db_password_out -e 'connect'"

  run_command "$command" "" "fail"
}


##############################################################################
check_for_destination_db()
##############################################################################
{
  printf "\n\n${TXT_NOTICE}## Checking if destination database exists: \"$destination_db\"${TXT_NORMAL}\n"

  # check if destination database exists
  command="mysql --batch --skip-column-names -u '$db_username'$db_password_out -e 'SHOW DATABASES LIKE \"$destination_db\"' | grep -q '$destination_db'"

  run_command "$command" "" "silent"
  return_code=$?

  if [[ $return_code -eq 0 ]]; then
    printf "${TXT_NOTICE}## Destination database exists${TXT_NORMAL}\n"
    return 0
  else
    printf "${TXT_NOTICE}## Destination database does not exist${TXT_NORMAL}\n"
    return 1
  fi
}


##############################################################################
backup_destination_db()
##############################################################################
{
  check_for_destination_db
  return_code=$?

  if [[ $return_code -eq 0 ]]; then
    printf "${TXT_NOTICE}## Backing up: \"$destination_db\"${TXT_NORMAL}\n"

    # set destination output filename
    destination_db_output=$(output_filename 'destination' "$destination_db")

    command="mysqldump -u '$db_username'<password> '$destination_db'"

    output_command "$command" "$destination_db_output"
    run_command "$command" "$destination_db_output" "fail"

    optionally_compress_file "destination_db_output"    # sets $destination_db_output to new filename

  else
    printf "${TXT_NOTICE}## Skipping backup${TXT_NORMAL}\n"
  fi
}


##############################################################################
create_destination_db()
##############################################################################
{
  printf "\n\n${TXT_NOTICE}## Creating empty destination database: \"$destination_db\"${TXT_NORMAL}\n"

  command="mysql -u '$db_username'<password> -e 'DROP DATABASE IF EXISTS \`$destination_db\`; CREATE DATABASE \`$destination_db\` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;'"

  output_command "$command"
  run_command "$command" "" "fail"
}


##############################################################################
copy_source_to_destination_db()
##############################################################################
{
  source_file="$1"

  printf "\n\n${TXT_NOTICE}## Copying source to destination database: \"$destination_db\"${TXT_NORMAL}\n"

  output_source_file_command=$(output_source_file_command "$source_file")
  return_code=$?

  case $return_code in
    0)
      command="$output_source_file_command | mysql -u '$db_username'<password> '$destination_db'"
      output_command "$command"
      run_command "$command" "$outfile" "fail"
      ;;
    $E_SOURCE_FILE_NOT_FOUND)
      error="source file not found"
      ;;
    $E_CANT_READ_SOURCE_FILE)
      error="cannot read source file"
      ;;
    $E_SOURCE_TYPE_ERROR)
      error="source format not supported"
      ;;
    $E_INVALID_SOURCE_FILE)
      error="invalid source file"
      ;;
    *)
      error="problem with source file"
      ;;
  esac

  if [[ $return_code -ne 0 ]]; then
    output="${TXT_ERROR}$COMMAND: ${error}: \"${source_file}\"${TXT_NORMAL}\n"
    printf "$output"
    printf "${TXT_ERROR}###   [ FAIL ]   ###${TXT_NORMAL}\n"
    exit $E_FAIL_ERROR
  fi
}


##############################################################################
# call main function
##############################################################################

main "$@"
