#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo "usage: $0 <source_database> <destination_database>" >&2
  exit 1
fi

source_db=$1
destination_db=$2
date=$(date +%F.%T)
source_db_output="output.$source_db.$date.sql"
destination_db_output="output.$destination_db.$date.sql"

if [[ $destination_db =~ '_prod' ]]; then
  echo -e "\n*******************************************************************************"
  echo -e "*                            !!!!!  WARNING !!!!!                             *"
  echo -e "*                                                                             *"
  echo -e "* This script will overwrite a PRODUCTION database ($destination_db)"
  echo -e "* with the contents of another database ($source_db)."
  echo -e "*                                                                             *"
  echo -e "* Are you sure you want to do this?  If so, confirm by entering \"CONFIRM\" in  *"
  echo -e "* all caps (without the quotes) at the prompt below.                          *"
  echo -e "*******************************************************************************"
  echo -e "\n"
  read -p "Are you sure? " confirm

  if [ $confirm != "CONFIRM" ]; then
    echo -e "## Exiting program without making any changes\n"
    exit
  fi
fi

read -s -p "DB Password: " db_password
echo -e ""

echo -e "\n\n## Backing up destination database: $destination_db"
echo -e "> mysqldump -u root -p<password> $destination_db > $destination_db_output"
mysqldump -u root -p$db_password $destination_db > $destination_db_output

echo -e "\n\n## Creating empty destination database: $destination_db"
echo -e "> mysql -u root -p<password> -e \"DROP DATABASE IF EXISTS \\\`$destination_db\\\`; CREATE DATABASE \\\`$destination_db\\\` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;\""
mysql -u root -p$db_password -e "DROP DATABASE IF EXISTS \`$destination_db\`; CREATE DATABASE \`$destination_db\` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;"

echo -e "\n\n## Creating dump of source database: $source_db"
echo -e "> mysqldump -u root -p<password> $source_db > $source_db_output"
mysqldump -u root -p$db_password $source_db > $source_db_output

echo -e "\n\n## Copying source database dump to destination database: $destination_db"
echo -e "> mysql -u root -p<password> $destination_db < $source_db_output"
mysql -u root -p$db_password $destination_db < $source_db_output

echo -e "\n"
